import React from 'react';

function Posts() {
  return (
    <>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
      <div>Post</div>
    </>
  );
}

export default Posts;